# Pipeline inicial
# Comece com um pipeline mínimo que você pode personalizar para compilar e implantar seu código.
# Adicione etapas que compilam, executam testes, implantam e muito mais:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './APITempoAZ204/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Instalar .NET SDK'
  inputs: 
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Restaurar Solução'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Compilar Solução'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"xPlat Code Coverage"
  displayName: 'Testar Solução'

- task: Docker@2
  displayName: 'Construir e Enviar Imagem Docker'
  inputs:
    containerRegistry: 'acrapiaz204vicssb'
    repository: 'api-az-204'
    command: 'buildAndPush'
    Dockerfile: './APITempoAZ204/Dockerfile'
